// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs72-5a9vXQAabHrYfS8cv4Zm0woUZcus',
    appId: '1:809155453829:android:5ed2a09d2d32776ac99aec',
    messagingSenderId: '809155453829',
    projectId: 'gridguardian-ce288',
    databaseURL: 'https://gridguardian-ce288-default-rtdb.firebaseio.com',
    storageBucket: 'gridguardian-ce288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtnb-0_ndfHvJg6_BG4MOYWKV8izWB71o',
    appId: '1:809155453829:ios:27415d8241047bd9c99aec',
    messagingSenderId: '809155453829',
    projectId: 'gridguardian-ce288',
    databaseURL: 'https://gridguardian-ce288-default-rtdb.firebaseio.com',
    storageBucket: 'gridguardian-ce288.firebasestorage.app',
    iosBundleId: 'com.example.gridguardian',
  );
}
